### ISSUE TITLE
The service has a dependency on a non-existent service "".

### ISSUE THREAD

**Issue by Avtonom** [fattouchsquall/AMFWebServicesClientBundle#3]
**The service "amf_web_services_client.soap.my_services" has a dependency on a non-existent service "".**

I hav in \app\config\config.yml

``` yml
amf_web_services_client:
    soap:
        endpoints:
            my_services:
                class: Web\GateBundle\Soap\MyClass
```

in \src\Web\GateBundle\Resources\config\services.yml :

``` yml
services:
    amf_web_services_client.soap.my_services:
        class: Web\GateBundle\Soap\MyClass
```

**Comment by fattouchsquall** [comment]
Hi, you don't need to reconfigure the service for the soap class, the service will be automatically named  **amf_web_services_client.soap.my_services**. You'll must omit the lines in services.yml.

**Comment by Avtonom** [comment]
``` yml
services:
#    amf_web_services_client.soap.my_services:
#        class: Web\GateBundle\Soap\MyClass
```

if you offer as it did not help.

**Comment by fattouchsquall** [comment]
Have you specified your wsdl file?

**Comment by Avtonom** [comment]
yes

``` yml
wsdl: "%kernel.root_dir%/../src/Web/Wsdl/file.wsdl"
```

**Comment by fattouchsquall** [comment]
as this?

``` yml
amf_web_services_client:
    soap:
        endpoints:
            my_services:
                class: Web\GateBundle\Soap\MyClass
                wsdl: "%kernel.root_dir%/../src/Web/Wsdl/file.wsdl"
```
